# Generated by Django 5.0.6 on 2024-05-19 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField()),
                ('month', models.CharField(max_length=20)),
                ('days_present', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmpBasicPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField()),
                ('basic_pay', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmpIncomeTax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_no', models.IntegerField()),
                ('income_tax_percentage', models.FloatField()),
            ],
        ),
    ]
